spring:
  mail:
    host: smtp.163.com
    port: 465  # 或 994
    username: kxyatxy116@163.com
    password: LAVDk33zXjXPcSGu  # 必须是SMTP授权码，非登录密码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          connection timeout: 5000
          timeout: 5000
          write timeout: 5000

  #数据库文件
  datasource:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/myblog?useSSL=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update # 自动更新表结构
    show-sql: true  # 显示SQL语句（调试用）
    open-in-view: false

  application:
    name: MyBlog

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

#  web:
    #resources:
      #static-locations: classpath:/static/ # 自定义静态资源路径

server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      force: true
  address: 0.0.0.0
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file:
    name: app.log