name: Debug SSH Connection

on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: List loaded keys
        run: ssh-add -l

      - name: Test SSH connection
        run: ssh -T -v git@github.com
