name: Deploy to Tencent Cloud Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # 确保变量名一致

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
          sudo apt update -y
          sudo apt install -y maven openjdk-17-jdk
          if [ ! -d "/home/ubuntu/MyBlog" ]; then
            git clone git@github.com:kxyzarsy/MyBlog.git /home/ubuntu/MyBlog
          fi
          cd /home/ubuntu/MyBlog
          git pull origin master
          mvn clean package -DskipTests
          sudo systemctl restart myblog
          EOF