name: Debug SSH

on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


      - name: Show public key fingerprint
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
          ssh-keygen -lf key.pem

      - name: Test SSH connection
        run: ssh -T -v git@github.com